USB_VID = 0x1209
USB_PID = 0x4203
USB_PRODUCT = "Splinky"
USB_MANUFACTURER = "plut0nium"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "GD25Q80C"

CIRCUITPY_ANALOGIO = 0
CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_AUDIOBUSIO_I2SOUT = 0
CIRCUITPY_AUDIOCORE = 0
CIRCUITPY_AUDIOIO = 0
CIRCUITPY_AUDIOMIXER = 0
CIRCUITPY_AUDIOMP3 = 0
CIRCUITPY_AUDIOPWMIO = 0
# CIRCUITPY_BITBANG_APA102 = 0
# CIRCUITPY_BITBANGIO = 0
# CIRCUITPY_BITBANGIO = 0
# CIRCUITPY_DISPLAYIO = 0
# CIRCUITPY_FRAMEBUFFERIO = 0
# CIRCUITPY_KEYPAD = 0
CIRCUITPY_RGBMATRIX = 0
CIRCUITPY_PS2IO = 0
CIRCUITPY_BLEIO_HCI=0
CIRCUITPY_BLEIO=0

# INTERNAL_FLASH_FILESYSTEM = 1
# LONGINT_IMPL = NONE

# CIRCUITPY_FULL_BUILD = 0

# CIRCUITPY_ANALOGIO = 0
# CIRCUITPY_AUDIOBUSIO = 0
# CIRCUITPY_AUDIOBUSIO_I2SOUT = 0
# CIRCUITPY_AUDIOCORE = 0
# CIRCUITPY_AUDIOIO = 0
# CIRCUITPY_AUDIOMIXER = 0
# CIRCUITPY_AUDIOMP3 = 0
# CIRCUITPY_AUDIOPWMIO = 0

# CIRCUITPY_BITMAPTOOLS = 0
# CIRCUITPY_BITMAPTOOLS = 0
# CIRCUITPY_BLEIO = 0
# CIRCUITPY_BUSDEVICE = 0
# CIRCUITPY_FRAMEBUFFERIO = 0
# CIRCUITPY_FREQUENCYIO = 0
# CIRCUITPY_GAMEPAD = 0
# CIRCUITPY_GAMEPADSHIFT = 0
# CIRCUITPY_I2CPERIPHERAL = 0
# CIRCUITPY_MATH = 0
# CIRCUITPY_MSGPACK = 0
# CIRCUITPY_NEOPIXEL_WRITE = 0
# CIRCUITPY_NVM = 0
# CIRCUITPY_PIXELBUF = 0
# CIRCUITPY_PS2IO = 0
# CIRCUITPY_PULSEIO = 0
# CIRCUITPY_PWMIO = 0
# CIRCUITPY_RGBMATRIX = 0
# CIRCUITPY_ROTARYIO = 0
# CIRCUITPY_ROTARYIO = 0
# CIRCUITPY_RTC = 0
# CIRCUITPY_SAMD = 0
# CIRCUITPY_ULAB = 0
# CIRCUITPY_USB_HID = 0
# CIRCUITPY_USB_MIDI = 0
# CIRCUITPY_USB_VENDOR = 0
# CIRCUITPY_VECTORIO = 0
